<h2>Listado de categorías</h2>

<a href="<?php echo APP_URL."categorias/add/"; ?>">Agregar categoría</a>
<table border="1">
	<tr>
		<th>ID</th>
		<th>NOMBRE</th>
		<th>ACCION</th>
	
	</tr>
	<?php foreach ($this->categorias as $categoria): ?> 	
	<tr>
		<td><?php echo $categoria['id']; ?></td>
		<td><?php echo $categoria['nombre']; ?></td>
		<td>
			<a href="<?php echo APP_URL."categorias/edit/".$categoria['id'];?>">Editar</a>
			<a href="<?php echo APP_URL."categorias/delete/".$categoria['id'];?>">Eliminar</a>
		</td>
	</tr>
	<?php endforeach ?>
</table>