<h2>Editar treas</h2>
<form action="<?php echo APP_URL. 'tareas/edit' ?>" method="post">
	<input type="hidden" name="id" 	value ="<?php echo $this->tarea['id']?>">
	<p>Nombre: <input 	type="text" name="nombre" value ="<?php echo $this->tarea['nombre']?>" ></p>
	<p>Fecha: <input 	type="text" name ="fecha" value ="<?php echo $this->tarea['fecha']?>"></p>
	<p>Prioridad:<input type="text" name="prioridad" value ="<?php echo $this->tarea['prioridad']?>"></p>
	
	<p>Categoría:
		<select name="categoria_id">
		<?php foreach ($this->categorias as $categoria): 
			if($categoria["id"]==$this->tarea["categoria_id"]) { 
				echo($categoria['id']);
				?>
				<option value = "<?php echo $categoria['id']; ?>" selected>
					<?php echo $categoria['nombre'] ?>
				</option>
			<?php }else{ ?>
				<option value="<?php echo $categoria["id"]; ?>">
					<?php echo $categoria['nombre']; ?>
				</option>
		<?php } endforeach?>
	</select>
	</p>

	<p>Estatus: <input 	type="text" name ="status" value ="<?php echo $this->tarea['status']?>"></p>
	<p><input type="submit"> </p>
	
</form>
